---
language: ruby
sudo: false
cache: bundler
bundler_args: --without metrics
script: rake test:coverage:run
rvm:
  - '1.9.3'
  - '2.0'
  - '2.1'
  - '2.2'
  - ruby-head
  - rbx-2 --1.9
  - rbx-2 --2.0
  - jruby-9.0.0.0.pre1
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
